allowedOrigin: https://chat.kulseng.no
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chat
    driverClassName: org.mariadb.jdbc.Driver
    username: DB_USERNAME
    password: DB_PASSWORD
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  ssl:
    certificate-private-key: /home/ubuntu/ssl/privkey.pem
    certificate: /home/ubuntu/ssl/cert.pem