name: Deploy
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Build Image
    runs-on: ubuntu-latest
    environment: Test
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'

    - name: Run unit test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  deploy:
    name: Deploy to production
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: ./deploy-spring.sh
